CREATE TABLE "Words" (
	"ID"	INT NOT NULL,
	"synonym"	TEXT NOT NULL,
	"synonym_ar"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (1, 'la famille', '«·⁄«∆·…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (2, 'une table', 'ÿ«Ê·…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (3, 'un stylo', 'ﬁ·„');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (4, 'un livre', 'ﬂ «»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (5, 'un cartable', 'ÕﬁÌ»…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (6, 'un travailleur', '⁄«„·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (7, 'un vendeur', '»«∆⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (8, 'un photographe', '„’Ê—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (9, 'une secrÈtaire', '«·”ﬂ—Ì Ì—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (10, 'un pompier', '—Ã· «·«ÿ›«¡');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (11, 'poule', 'œÃ«Ã…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (12, 'lapin', '√—‰»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (13, 'mouton', 'Œ—Ê›');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (14, 'pigeon', 'Õ„«„…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (15, 'vache', '»ﬁ—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (16, 'la mËre', '«·√„');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (17, 'le pËre', '«·√»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (18, 'le bÈbÈ', '«·—÷Ì⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (19, 'l''enfant', '«·ÿ›·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (20, 'un banquier', '„ÊŸ› »‰ﬂ („’—›Ì)');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (21, 'un Ècrivain', 'ﬂ« »');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (22, 'un coiffeur', '„’›› «·‘⁄— «Ê «·ÕÃ«„');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (23, 'musicien', '«·„Ê”Ìﬁ«—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (24, 'un voleur', '«··’');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (25, 'un facteur', '”«⁄Ì «·»—Ìœ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (26, 'un mÈcanicien', '«·„Ìﬂ«‰ÌﬂÌ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (27, 'un directeur', '„œÌ—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (28, 'programmeur', '„»—„Ã');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (29, 'designer', '„’„„');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (30, 'un menuisier', '«·‰Ã«—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (31, 'un plombier', '«·”„ﬂ—Ì');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (32, 'un dentiste', 'ÿ»Ì» «”‰«‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (33, 'un fleuriste', '»«∆⁄ «·“ÂÊ—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (34, 'une hÙtesse de l''air', '„÷Ì›… ÃÊÌ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (35, 'un pilote', 'ÿÌ«—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (36, 'un fermier', '„“«—⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (37, 'un homme d''affaires', '—Ã· «⁄„«·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (38, 'architecte', '„Â‰œ”');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (39, 'assistant', '„”«⁄œ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (40, 'auteur', '„ƒ·›');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (41, 'comptable', '„Õ«”»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (42, 'journaliste', '’Õ›Ì');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (43, 'infirmier', '„„—÷');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (44, 'mÈdecin', 'ÿ»Ì»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (45, 'un pantalon', '»‰ÿ«·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (46, 'une maison', '„‰“·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (47, 'un appartement', '‘ﬁ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (48, 'une piËce', '€—›…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (49, 'une fenÍtre', '‰«›–…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (50, 'des meubles', '√À«À');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (51, 'un escalier', 'œ—Ã');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (52, 'un balcon', '‘—›…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (53, 'une chemise', 'ﬁ„Ì’');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (54, 'un bureau', '„ﬂ »');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (55, 'un lit', '”—Ì—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (56, 'une commode', 'Œ“«‰…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (57, 'une veste', '” —…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (58, 'un ordinateur', 'ﬂ„»ÌÊ —');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (59, 'un tÈlÈphone', 'Â« ›');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (60, 'une ÈtagËre', '—›');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (61, 'une lampe', '„’»«Õ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (62, 'la machine ‡ laver', '¬·… «·€”Ì·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (63, 'le fer ‡ repasser', '«·„ﬂÊ«…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (64, 'le balai', '«·„ﬂ‰”…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (65, 'la pelle', '«·„Ã—›…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (66, 'la brosse', '«·›—‘«…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (67, 'le vaporisateur', '«·»Œ«Œ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (68, 'le seau', '«·œ·Ê');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (69, 'les ordures', 'ﬁ„«„…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (70, 'la poubelle', '”·… «·„Â„·« ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (71, 'un tÈlÈviseur', ' ·›“ÌÊ‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (72, 'un tableau', '·ÊÕ… ›‰Ì…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (73, 'un tapis', '”Ã«œ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (74, 'un canapÈ', '√—Ìﬂ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (75, 'un fauteuil', 'ﬂ—”Ì');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (76, 'un rocking-chair', 'ﬂ—”Ì Â“«“');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (77, 'une bibliothËque', '„ﬂ »…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (78, 'des instruments de musique', '¬·«  „Ê”ÌﬁÌ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (79, 'un buffet', '»Ê›ÌÂ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (80, 'le couteau', '«·”ﬂÌ‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (81, 'la fourchette', '«·‘Êﬂ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (82, 'le verre', '«·ﬂÊ»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (83, 'la poivriËre', '«·›·›·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (84, 'une assiette', '’Õ‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (85, 'la cuillËre', '«·„·⁄ﬁ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (86, 'la carafe', 'ﬁ‰Ì‰…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (87, 'la serviette', '«·„‰‘›…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (88, 'la saliËre', '«·„„·Õ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (89, 'la bouteille', '«·“Ã«Ã…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (90, 'les fruits', '«·›«ﬂÂ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (91, 'les cerises', 'ﬂ—“');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (92, 'fraises', '›—«Ê·…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (93, 'le citron', '«··Ì„Ê‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (94, 'la pomme', '«· ›«Õ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (95, 'l''orange', '«·»— ﬁ«·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (96, 'la poire', '«·ﬂ„À—Ï');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (97, 'la banane', '«·„Ê“');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (98, 'les raisins', '«·⁄‰»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (99, 'la pastËque', '«·»ÿÌŒ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (100, 'l''ananas', '«·√‰«‰«”');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (101, 'la prune', '«·ŒÊŒ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (102, 'l''ail', '«·ÀÊ„');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (103, 'les oignons', '«·»’·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (104, 'les pommes de terre', '«·»ÿ«ÿ«');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (105, 'les feves', '«·›Ê·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (106, 'l''ours', '«·œ»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (107, 'serpent', 'À⁄»«‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (108, 'tigre', '‰„—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (109, 'lion', '√”œ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (110, 'une cravate', '—»ÿ… ⁄‰ﬁ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (111, 'aigle', '‰”—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (112, 'singe', 'ﬁ—œ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (113, 'crocodile', ' „”«Õ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (114, 'renard', 'À⁄·»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (115, 'guÈpard', '›Âœ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (116, 'hyËne', '÷»⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (117, 'loup', '–∆»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (118, 'gazelle', '€“«·…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (119, 'Ècureuil', '”‰Ã«»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (120, 'ÈlÈphant', '›Ì·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (121, 'girafe', '“—«›…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (122, 'hippopotame', '›—” «·‰Â—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (123, 'panda', '»«‰œ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (124, 'rhinocÈros', 'ÊÕÌœ «·ﬁ—‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (125, 'tortue', '”·Õ›«…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (126, 'zËbre', 'Õ„«— ÊÕ‘Ì');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (127, 'ane', 'Õ„«—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (128, 'boeuf', '⁄Ã·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (129, 'canard', '»ÿ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (130, 'chameau', 'Ã„·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (131, 'chat', 'ﬁÿ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (132, 'cheval', 'Õ’«‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (133, 'chËvre', '„«⁄“');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (134, 'chien', 'ﬂ·»');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (135, 'cochon', 'Œ‰ÊÌ—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (136, 'coq', 'œÌﬂ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (137, 'le cerveau', '«·œ„«€');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (138, 'le bras', '–—«⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (139, 'le dos', '«·ŸÂ—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (140, 'la barbe', '·ÕÌ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (141, 'un chapeau', 'ﬁ»⁄…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (142, 'le doigt', '«·√’»⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (143, 'les cheveux', '«·‘⁄—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (144, 'la voiture', '«·”Ì«—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (145, 'le camion', '«·‘«Õ‰…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (146, 'le mÈtro', '«·„ —Ê');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (147, 'líhÈlicoptËre', 'Â·ÌﬂÊ» —');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (148, 'la bateau', '«·»«Œ—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (149, 'la moto', 'œ—«Ã… ‰«—Ì…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (150, 'le vÈlo', '«·œ—«Ã…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (151, 'la fusÈe', '«·’«—ÊŒ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (152, 'la sous-marin', '«·€Ê«’…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (153, 'le ciel', '«·”„«¡');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (154, 'le lac', '«·»ÕÌ—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (155, 'le volcan', '«·»—ﬂ«‰');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (156, 'líarbre', '«·‘Ã—…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (157, 'le soleil', '«·‘„”');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (158, 'le jardin', '«·ÕœÌﬁ…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (159, 'le nuage', '«·”Õ«»…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (160, 'le fleuve', '«·‰Â—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (161, 'la mer', '«·»Õ—');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (162, 'la montagne', '«·Ã»·');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (163, 'la plage', '«·‘«ÿ∆');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (164, 'la neige', '«·Ã·Ìœ');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (165, 'la grenouille', '«·÷›œ⁄');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (166, 'la forÍt', '«·€«»…');
INSERT INTO Words (ID, synonym, synonym_ar) VALUES (167, 'les fleurs', '«·“ÂÊ—')